
export const UPDATE_CHIP_POSITION= 'UPDATE_CHIP_POSITION';
export const UPDATE_POINTS_WINNER= 'UPDATE_POINTS_WINNER';
export const CONTINUE_GAME= 'CONTINUE_GAME';
export const RESET_GAME= 'RESET_GAME';